# Production docker-compose configuration
# Usage: docker-compose -f docker-compose.prod.yml up -d

services:
  # FastAPI Application (Production)
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: blog-post-manager:latest
    container_name: blog_api_prod
    environment:
      DATABASE_URL: ${DATABASE_URL}  # Must be provided externally
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}  # Must be provided externally
      JWT_ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 15
      REFRESH_TOKEN_EXPIRE_DAYS: 7
      CORS_ORIGINS: ${CORS_ORIGINS:-https://yourdomain.com}
      ENVIRONMENT: production
      LOG_LEVEL: INFO
      DB_POOL_SIZE: 20
      DB_MAX_OVERFLOW: 40
      RATE_LIMIT_PER_MINUTE: 100
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    networks:
      - blog_network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  blog_network:
    driver: bridge
